package cricketenthusiast;

public enum SortingFields {
    POSITION, PLAYER, MATCHES, AVERAGE, BAT_STRIKE_RATE, BALL_STRIKE_RATE, SIX_AND_FOURS, RUNS, ECONOMY, WICKETS_FIVES_FOURES, BALL_STRIKE_RATE_WITH_WICKETS
}
